version: "3"
services:
  db:
    image: "mariadb:10.6.15"
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "okstar"
  apacheds:
    build:
      context: ./apacheds
    ports:
      - 10389:10389
  keycloak:
    build:
      context: ./keycloak
    environment:
      - KC_DB=mariadb
      - KC_DB_URL=jdbc:mariadb://db/keycloak?autoReconnect=true&useUnicode=true&characterEncoding=utf8
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=okstar
      - KC_HOSTNAME=localhost
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=okstar
    ports:
      - 8080:8080
      - 8443:8443
      - 10990:10990
    depends_on:
      - apacheds
      - db
  openfire:
    image: okstar-openfire:v4.7
    ports:
      - 3478:3478
      - 3479:3479
      - 5222:5222
      - 5223:5223
      - 5229:5229
      - 5262:5262
      - 5263:5263
      - 5275:5275
      - 5276:5276
      - 7070:7070
      - 7443:7443
      - 7777:7777
      - 9090:9090
      - 9091:9091
      - 5005:5005
    depends_on:
      - db

