version: "3"
services:
  db:
    image: "mariadb:10.6.15"
    container_name: "db"
    ports:
      - "3306:3306"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
      - ./mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "okstar"

  apacheds:
    build:
      context: ./apacheds
    container_name: "apacheds"
    ports:
      - 10389:10389
  #    volumes:
  #      - ./apacheds/data:/var/lib/apacheds-2.0.0.AM26

  keycloak:
    build:
      context: ./keycloak
    container_name: "keycloak"
    environment:
      - KC_DB=mariadb
      - KC_DB_URL=jdbc:mariadb://db/keycloak?autoReconnect=true&useUnicode=true&characterEncoding=utf8
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD={password}
      - KC_HOSTNAME_URL=https://kc.okstar.org.cn
      - KC_HOSTNAME_ADMIN_URL=https://kc.okstar.org.cn
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=okstar
      - KEYCLOAK_SAME_SITE_COOKIES=true
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_HTTPS_PORT=443
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
        #    security_opt:
      #- seccomp:unconfined
    ports:
      - 8043:8080
      - 8443:8443
      - 10990:10990
    depends_on:
      - apacheds
      - db
  openfire:
    image: okstar-openfire:v4.7
    container_name: "openfire"
    ports:
      - 3478:3478
      - 3479:3479
      - 5222:5222
      - 5223:5223
      - 5229:5229
      - 5262:5262
      - 5263:5263
      - 5275:5275
      - 5276:5276
      - 7070:7070
      - 7443:7443
      - 7777:7777
      - 9090:9090
      - 9091:9091
      - 5005:5005
    depends_on:
      - db
      - apacheds

  gateway:
    image: "flytreeleft/nginx-gateway"
    container_name: "gateway"
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/logs:/var/log/nginx/sites
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/stream.d:/etc/nginx/stream.d
      - ./nginx/epage.d:/etc/nginx/epage.d
    ports:
      - 8080:80
