services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USE: postgres
      POSTGRES_PASSWORD: okstar
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
