name: Build on Ubuntu 22.04 platforms

permissions:
  contents: write
  discussions: write

on:
  push:
    branches: [ "develop-ci" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        arch: [x64]
        os: [ubuntu-22.04]
        build_type: [Release]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: ${{ matrix.arch }}

      - name: Pull submodules
        run: |
          git submodule update --remote --init

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      - name: Build with Maven
        run: mvn clean package